root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  # possible problems
  no-duplicate-imports: 2
  no-template-curly-in-string: 2
  no-unreachable-loop: 2

  # suggestions
  arrow-body-style: [2, always]
  curly: 2

  # layout and formatting
  arrow-parens: 2
  arrow-spacing: 2
  comma-dangle: [2, always-multiline]
  comma-spacing: 2
  eol-last: 2
  indent: [2, tab]
  keyword-spacing: 2
  no-multi-spaces: 2
  no-multiple-empty-lines: 2
  no-trailing-spaces: 2
  object-curly-spacing: [2, always]
  quotes: [2, single, allowTemplateLiterals: true]
  semi: [2, never]

  '@typescript-eslint/no-empty-function': 0
